# start pane index at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
# fixes tmux colors:
set-option -sa terminal-overrides ",xterm*:Tc"
# different leader key:
unbind C-b
set -g prefix C-Space
bind C-space send-prefix
# enable mouse usage
set -g mouse on
# another vim keys thing
set -g mode-keys vi
# open panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
# plugins:
set -g @plugin 'tmux-plugins/tpm' # tmux plugin manager
set -g @plugin 'tonylambiris/palenight-tmux' # palenight colortheme
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator' # use vimbindings to navigate
set -g @plugin 'tmux-plugins/tmux-yank' # properly copy within split panes in tmux
set -g @plugin 'tmux-plugins/tmux-resurrect' # save tmux sessions between boots
set -g @resurrect-auto-save 'yes' # autosave enable for tmux resurrect

run '~/.tmux/plugins/tpm/tpm'
