# APPEARENCE CONFIG
# 
# cursor smear animation
cursor_trail 1
#
#------------------------------------------------
# FUNCTIONALITY CONFIG
# no prompt when exiting kitty
confirm_os_window_close 0


# BEGIN_KITTY_THEME
# Dracula
include current-theme.conf
# END_KITTY_THEME