# APPEARENCE CONFIG
# 
# cursor smear animation
cursor_trail 1
# self explanatory
font_family FiraCode Nerd Font
font_size 14.0
enable_ligatures always
background_opacity 0.95
window_padding_width 4
#------------------------------------------------
# FUNCTIONALITY CONFIG
# no prompt when exiting kitty
confirm_os_window_close 0
# idk what this does tbh
shell_integration zsh
# self explanatory
scrollback_lines 10000
#------------------------------------------------
# BEGIN_KITTY_THEME
# Dracula
include current-theme.conf
# END_KITTY_THEME
