window:
  padding:
    x: 6
    y: 4
  opacity: 0.85
  decorations: "None"

font:
  normal:
    family: "FiraCode Nerd Font"
    style: Regular
  bold:
    family: "FiraCode Nerd Font"
    style: Bold
  italic:
    family: "FiraCode Nerd Font"
    style: Italic
  size: 12.0
